const{EmbedBuilder:E,ActionRowBuilder:R,ButtonBuilder:B,ButtonStyle:S,StringSelectMenuBuilder:SM}=require("discord.js");
const SEV={critical:{e:"🔴",c:0xff0000,l:"Critical",b:"████████"},high:{e:"🟠",c:0xff8c00,l:"High",b:"██████░░"},medium:{e:"🟡",c:0xffd700,l:"Medium",b:"████░░░░"},low:{e:"🟢",c:0x00cc00,l:"Low",b:"██░░░░░░"}};
const ST={"open":{e:"📋",l:"Open"},"in-progress":{e:"🔧",l:"In Progress"},"resolved":{e:"✅",l:"Resolved"},"closed":{e:"🔒",l:"Closed"}};
const CT={gameplay:"🎮 Gameplay",graphics:"🖼️ Graphics",audio:"🔊 Audio",network:"🌐 Network",performance:"⚡ Performance",save:"💾 Save",ai:"🤖 AI",other:"📦 Other"};
const PL={pc:"🖥️ PC",playstation:"🎮 PS",xbox:"🎮 Xbox",mobile:"📱 Mobile",all:"🌐 All"};

// VERIFY
const verifyP=()=>new E().setColor(0x2ecc71).setAuthor({name:"VERIFICATION"}).setTitle("━━━━━━ Server Verification ━━━━━━").setDescription("```\n   Welcome to the server!\n   Accept the rules to continue.\n```\n\n**Rules:**\n> 1. Be respectful to others\n> 2. No spam or flooding\n> 3. No advertising\n> 4. No NSFW content\n> 5. Follow staff decisions\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nClick below to accept the rules.").setFooter({text:"Studio Bot v7"}).setTimestamp();
const verifyB=()=>new R().addComponents(new B().setCustomId("verify_accept").setLabel("  I Accept the Rules  ").setStyle(S.Success).setEmoji("✅"));

// BUG PANEL
const bugP=()=>new E().setColor(0x5865f2).setAuthor({name:"BUG TRACKER"}).setTitle("━━━━━━━━ Bug Reports ━━━━━━━━").setDescription("```\n    Found a bug in the game?\n    Click below to report it!\n```\n\n🔴 `CRITICAL` Game crashes\n🟠 `HIGH    ` Major issue\n🟡 `MEDIUM  ` Tolerable\n🟢 `LOW     ` Cosmetic\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n> Each bug report earns **+30 XP**!\n> Critical bugs auto-ping the dev team.").setFooter({text:"Studio Bot v7"}).setTimestamp();
const bugBP=()=>[new R().addComponents(new B().setCustomId("open_report").setLabel("  Report Bug  ").setStyle(S.Danger).setEmoji("🐛")),new R().addComponents(new B().setCustomId("my_bugs").setLabel("My Reports").setStyle(S.Secondary).setEmoji("📌"),new B().setCustomId("open_dash").setLabel("Dashboard").setStyle(S.Secondary).setEmoji("📊"),new B().setCustomId("open_lb").setLabel("Leaderboard").setStyle(S.Secondary).setEmoji("🏆"))];

// ADMIN
const adminP=(bs,ts,bt)=>new E().setColor(0x2f3136).setAuthor({name:"ADMIN CONTROL CENTER"}).setTitle("━━━━━━━━ Management Panel ━━━━━━━━").setDescription("```\n"+`  📋 Open Bugs   ${String(bs?.open||0).padStart(4)}    🔧 In Progress ${String(bs?.prog||0).padStart(4)}\n`+`  ✅ Resolved    ${String(bs?.resolved||0).padStart(4)}    🔒 Closed      ${String(bs?.closed||0).padStart(4)}\n`+`  🎫 Open Tickets${String(ts?.open||0).padStart(4)}    🔑 Key Pool    ${String(bt?.pool||0).padStart(4)}\n`+"```\n"+`🔴 **Critical:** ${bs?.critical||0} | 📊 **Total:** ${bs?.total||0}`).setTimestamp();
const adminBP=()=>[new R().addComponents(new B().setCustomId("a_bugs").setLabel("Bugs").setStyle(S.Primary).setEmoji("📋"),new B().setCustomId("a_crit").setLabel("Critical").setStyle(S.Danger).setEmoji("🚨"),new B().setCustomId("a_tkts").setLabel("Tickets").setStyle(S.Secondary).setEmoji("🎫"),new B().setCustomId("a_refresh").setLabel("Refresh").setStyle(S.Success).setEmoji("🔄")),new R().addComponents(new B().setCustomId("a_members").setLabel("Members").setStyle(S.Secondary).setEmoji("👥"),new B().setCustomId("a_automod").setLabel("AutoMod").setStyle(S.Secondary).setEmoji("🛡️"),new B().setCustomId("a_givs").setLabel("Giveaways").setStyle(S.Secondary).setEmoji("🎁"),new B().setCustomId("a_stats").setLabel("Stats").setStyle(S.Secondary).setEmoji("📈"))];

// TICKET
const tktP=(s)=>new E().setColor(0xe74c3c).setAuthor({name:"SUPPORT CENTER"}).setTitle("━━━━━━━━ Support Tickets ━━━━━━━━").setDescription("```\n   Need help?\n   Click a button to open a ticket!\n```\n\n🔧 `Technical` Game crashes/errors\n👤 `Account  ` Login/ban/account\n💰 `Payment  ` Purchase/refund\n❓ `General  ` Other questions\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"+`📊 Open: **${s?.open||0}** | Closed: **${s?.closed||0}**`).setFooter({text:"Support System"}).setTimestamp();
const tktBP=()=>[new R().addComponents(new B().setCustomId("tkt_technical").setLabel("Technical").setStyle(S.Danger).setEmoji("🔧"),new B().setCustomId("tkt_account").setLabel("Account").setStyle(S.Primary).setEmoji("👤"),new B().setCustomId("tkt_payment").setLabel("Payment").setStyle(S.Success).setEmoji("💰"),new B().setCustomId("tkt_general").setLabel("General").setStyle(S.Secondary).setEmoji("❓"))];
function tktE(t){const c={technical:0xe74c3c,account:0x3498db,payment:0x2ecc71,general:0x95a5a6};return new E().setColor(c[t.cat]||0x5865f2).setAuthor({name:t.tag}).setTitle({technical:"🔧 Technical Issue",account:"👤 Account Issue",payment:"💰 Payment Issue",general:"❓ General Question"}[t.cat]||t.cat).setDescription(`>>> ${t.desc.slice(0,500)}`).addFields({name:"Created by",value:`<@${t.uid}>`,inline:true},{name:"Status",value:t.status==="open"?"📋 Open":"🔒 Closed",inline:true},{name:"Claimed by",value:t.claimUid?`<@${t.claimUid}>`:"Not yet",inline:true}).setFooter({text:`${t.tag} | ${t.at}`});}

// SUGGESTION
const sugP=()=>new E().setColor(0xf39c12).setAuthor({name:"SUGGESTIONS & FEEDBACK"}).setTitle("━━━━━━ Suggestions / Feedback ━━━━━━").setDescription("```\n   Have an idea for the game?\n   Share it and let the community vote!\n```\n\n🎮 `Gameplay  ` Mechanics\n🖼️ `Visual    ` Graphics, UI\n🌐 `Community ` Server, events\n📦 `Other     ` Misc\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n> Top voted suggestions are reviewed by the team!").setFooter({text:"Suggestion System"}).setTimestamp();
const sugBP=()=>[new R().addComponents(new B().setCustomId("sug_create").setLabel("  Submit Suggestion  ").setStyle(S.Success).setEmoji("💡")),new R().addComponents(new B().setCustomId("sug_top").setLabel("Most Popular").setStyle(S.Secondary).setEmoji("🔥"),new B().setCustomId("sug_mine").setLabel("My Suggestions").setStyle(S.Secondary).setEmoji("📌"))];
function sugC(s){const st={open:{e:"💡",l:"Open",c:0xf39c12},approved:{e:"✅",l:"Approved",c:0x00cc00},rejected:{e:"❌",l:"Rejected",c:0xff0000},planned:{e:"📋",l:"Planned",c:0x3498db},done:{e:"🎉",l:"Done",c:0x9b59b6}};const t=st[s.status]||st.open;const sc=(s.up?.length||0)-(s.dn?.length||0);const e=new E().setColor(t.c).setAuthor({name:`${s.tag} — ${t.e} ${t.l}`}).setTitle(s.title).setDescription(`>>> ${s.desc.slice(0,400)}`).addFields({name:"Score",value:`👍 ${s.up?.length||0}  👎 ${s.dn?.length||0}  (net: **${sc}**)`,inline:true},{name:"By",value:`<@${s.uid}>`,inline:true});if(s.resp)e.addFields({name:`${t.e} Team Response (${s.respBy})`,value:`>>> ${s.resp}`});e.setFooter({text:`${s.tag} | ${s.at}`});return e;}
const sugVB=(id)=>new R().addComponents(new B().setCustomId(`su_${id}`).setLabel("Support").setStyle(S.Success).setEmoji("👍"),new B().setCustomId(`sd_${id}`).setLabel("Oppose").setStyle(S.Secondary).setEmoji("👎"));
const sugAB=(id)=>new R().addComponents(new B().setCustomId(`sa_${id}`).setLabel("Approve").setStyle(S.Success).setEmoji("✅"),new B().setCustomId(`sp_${id}`).setLabel("Plan").setStyle(S.Primary).setEmoji("📋"),new B().setCustomId(`sr_${id}`).setLabel("Reject").setStyle(S.Danger).setEmoji("❌"),new B().setCustomId(`sx_${id}`).setLabel("Done").setStyle(S.Secondary).setEmoji("🎉"));

// BETA
const betaP=(s)=>new E().setColor(0x9b59b6).setAuthor({name:"CLOSED BETA PROGRAM"}).setTitle("━━━━━━━ Beta Application ━━━━━━━").setDescription("```\n   Want to join the closed beta?\n```\n\nApply below. If approved, you'll receive a **beta key** via DM.\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"+`🔑 Pool: **${s?.pool||0}** | 📨 Pending: **${s?.pending||0}**\n✅ Approved: **${s?.approved||0}** | ❌ Rejected: **${s?.rejected||0}**`).setFooter({text:"Beta Program"}).setTimestamp();
const betaBP=()=>[new R().addComponents(new B().setCustomId("beta_apply").setLabel("  Apply for Beta  ").setStyle(S.Success).setEmoji("🔑")),new R().addComponents(new B().setCustomId("beta_status").setLabel("My Status").setStyle(S.Secondary).setEmoji("📋"),new B().setCustomId("beta_stats").setLabel("Stats").setStyle(S.Secondary).setEmoji("📊"))];
const betaAP=(s)=>new E().setColor(0xe67e22).setAuthor({name:"BETA KEY MANAGEMENT"}).setTitle("━━━━━━━ Key Pool ━━━━━━━").setDescription("```\n"+`  🔑 Pool      ${String(s?.pool||0).padStart(4)}    📦 Distributed ${String(s?.used||0).padStart(4)}\n`+`  📨 Pending   ${String(s?.pending||0).padStart(4)}    ✅ Approved    ${String(s?.approved||0).padStart(4)}\n`+"```").setTimestamp();
const betaABP=()=>[new R().addComponents(new B().setCustomId("bk_add").setLabel("Upload Keys").setStyle(S.Success).setEmoji("🔑"),new B().setCustomId("bk_pending").setLabel("Pending").setStyle(S.Primary).setEmoji("📨"),new B().setCustomId("bk_used").setLabel("Distributed").setStyle(S.Secondary).setEmoji("📦"),new B().setCustomId("bk_refresh").setLabel("Refresh").setStyle(S.Secondary).setEmoji("🔄"))];
function betaC(a){const c={pending:0xf39c12,approved:0x00cc00,rejected:0xff0000};const l={pending:"⏳ Pending",approved:"✅ Approved",rejected:"❌ Rejected"};const e=new E().setColor(c[a.status]||0x5865f2).setAuthor({name:`BETA #${a.id}`}).setTitle(l[a.status]||a.status).addFields({name:"Applicant",value:`<@${a.uid}>`,inline:true},{name:"Platform",value:a.plat||"?",inline:true},{name:"Date",value:a.at,inline:true});if(a.reason)e.setDescription(`>>> ${a.reason.slice(0,500)}`);if(a.reviewer)e.addFields({name:"Reviewer",value:a.reviewer,inline:true});if(a.key)e.addFields({name:"Key",value:`\`${a.key.slice(0,5)}...\``,inline:true});return e;}
const betaCB=(id)=>new R().addComponents(new B().setCustomId(`bok_${id}`).setLabel("Approve").setStyle(S.Success).setEmoji("✅"),new B().setCustomId(`bno_${id}`).setLabel("Reject").setStyle(S.Danger).setEmoji("❌"));
const betaSE=(s)=>new E().setTitle("🔑 Beta Stats").setColor(0x9b59b6).setDescription("```\n"+`  🔑 Pool     ${String(s.pool).padStart(4)}    📨 Pending  ${String(s.pending).padStart(4)}\n`+`  ✅ Approved ${String(s.approved).padStart(4)}    ❌ Rejected ${String(s.rejected).padStart(4)}\n`+`  📦 Given    ${String(s.used).padStart(4)}\n`+"```").setTimestamp();

// REACTION ROLES
const rrP=()=>new E().setColor(0x3498db).setAuthor({name:"PLATFORM SELECT"}).setTitle("━━━━━━ Choose Your Platform ━━━━━━").setDescription("Which platform do you play on?\nClick to get your role. Click again to remove.\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nYou can select multiple.").setTimestamp();
const rrB=()=>[new R().addComponents(new B().setCustomId("rr_PC Player").setLabel("PC").setStyle(S.Secondary).setEmoji("🖥️"),new B().setCustomId("rr_PS Player").setLabel("PlayStation").setStyle(S.Secondary).setEmoji("🎮"),new B().setCustomId("rr_Xbox Player").setLabel("Xbox").setStyle(S.Secondary).setEmoji("🟢"),new B().setCustomId("rr_Mobile Player").setLabel("Mobile").setStyle(S.Secondary).setEmoji("📱"))];

// AUTOMOD
function amP(s){return new E().setColor(0xe74c3c).setAuthor({name:"AUTO-MODERATION"}).setTitle("━━━━━━━ AutoMod Settings ━━━━━━━").setDescription("```\n"+`  Banned Words       ${String(s.banned_words?.length||0).padStart(4)}\n`+`  Max Caps            %${s.max_caps||70}\n`+`  Max Mentions         ${s.max_mentions||5}\n`+`  Spam Protection      ${s.spam_count||5} msg / ${(s.spam_ms||3000)/1000}s\n`+"```\n\n`/automod-word add word`\n`/automod-word remove word`").setTimestamp();}
const amB=()=>new R().addComponents(new B().setCustomId("am_words").setLabel("Banned Words").setStyle(S.Danger).setEmoji("🚫"),new B().setCustomId("am_cfg").setLabel("Settings").setStyle(S.Secondary).setEmoji("⚙️"));

// GIVEAWAY
function givE(g){return new E().setColor(g.status==="active"?0xf39c12:0x95a5a6).setAuthor({name:"GIVEAWAY"}).setTitle(`🎁 ${g.prize}`).setDescription(g.status==="active"?`Click below to enter!\n\n**Ends:** <t:${Math.floor(new Date(g.ends).getTime()/1000)}:R>\n**Winners:** ${g.winCt}\n**Entries:** ${g.entries.length}`:`**Giveaway Ended!**\n\n**Winners:** ${g.winners.map(w=>`<@${w}>`).join(", ")||"None"}\n**Entries:** ${g.entries.length}`).setFooter({text:`#${g.id} | ${g.host}`}).setTimestamp();}
const givB=(id)=>new R().addComponents(new B().setCustomId(`ge_${id}`).setLabel("Enter").setStyle(S.Success).setEmoji("🎉"));

// POLL
function polE(p){const tot=p.opts.reduce((s,o)=>s+o.v.length,0)||1;let d=p.opts.map((o,i)=>{const pct=Math.round(o.v.length/tot*100);const bar="█".repeat(Math.round(pct/5))+"░".repeat(20-Math.round(pct/5));return`**${i+1}.** ${o.t}\n\`${bar}\` ${pct}% (${o.v.length})`;}).join("\n\n");if(p.ends&&p.status==="active")d+=`\n\n**Ends:** <t:${Math.floor(new Date(p.ends).getTime()/1000)}:R>`;return new E().setColor(p.status==="active"?0x3498db:0x95a5a6).setAuthor({name:p.status==="active"?"POLL":"POLL ENDED"}).setTitle(p.q).setDescription(d).setFooter({text:`#${p.id} | ${p.author}`}).setTimestamp();}
function polB(p){const rows=[];for(let i=0;i<p.opts.length;i+=4){const r=new R();for(let j=i;j<Math.min(i+4,p.opts.length);j++)r.addComponents(new B().setCustomId(`pv_${p.id}_${j}`).setLabel(`${j+1}. ${p.opts[j].t.slice(0,20)}`).setStyle(S.Secondary));rows.push(r);}return rows;}

// PROFILE
function profE(m,rank){const sc=m.invs*50+m.bugs*30+m.msgs;const pct=Math.round((m.xp%100));const bar="█".repeat(Math.round(pct/5))+"░".repeat(20-Math.round(pct/5));return new E().setColor(0x5865f2).setAuthor({name:"PLAYER PROFILE"}).setTitle(m.name||"Unknown").setDescription(`**Rank:** #${rank}\n**Score:** ${sc} pts\n\n**Level ${m.lvl}**\n\`${bar}\` ${m.xp} / ${(m.lvl+1)*100} XP`).addFields({name:"📨 Invites",value:`${m.invs||0}`,inline:true},{name:"🐛 Bugs",value:`${m.bugs||0}`,inline:true},{name:"💬 Messages",value:`${m.msgs||0}`,inline:true},{name:"📅 Joined",value:m.joined||"?",inline:true}).setFooter({text:"Score = Invites×50 + Bugs×30 + Messages"}).setTimestamp();}

// LEADERBOARD
function lbE(members){const m=["🥇","🥈","🥉"];return new E().setColor(0xf39c12).setAuthor({name:"LEADERBOARD"}).setTitle("━━━━━━━━ Top Players ━━━━━━━━").setDescription(members.slice(0,15).map((x,i)=>`${m[i]||`${i+1}.`} **${x.name}** — ${x.score} pts (📨${x.invs||0} 🐛${x.bugs||0} 💬${x.msgs||0})`).join("\n")||"No data yet.").setFooter({text:"Score = Invites×50 + Bugs×30 + Messages"}).setTimestamp();}

// BUG CARD
function bugE(b,h=[],c=[]){const sv=SEV[b.sev]||SEV.medium,st=ST[b.status]||ST.open;const e=new E().setColor(sv.c).setAuthor({name:`${b.tag} — ${st.e} ${st.l}`}).setTitle(b.title).setDescription(`>>> ${b.desc.slice(0,280)}`);if(b.steps)e.addFields({name:"Steps",value:`\`\`\`\n${b.steps.slice(0,400)}\n\`\`\``});e.addFields({name:"Severity",value:`${sv.e} \`${sv.b}\``,inline:true},{name:"Platform",value:PL[b.plat]||"?",inline:true},{name:"Category",value:CT[b.cat]||"?",inline:true},{name:"Reporter",value:`<@${b.by}>`,inline:true},{name:"Assigned",value:b.to?`<@${b.to}>`:"—",inline:true},{name:"Votes",value:`👍 ${b.votes?.length||0}`,inline:true});if(b.resNote)e.addFields({name:"Resolution",value:`>>> ${b.resNote.slice(0,400)}`});if(h.length)e.addFields({name:"History",value:h.slice(-5).map(x=>`\`${x.at}\` ▸ **${x.act}** (${x.by})`).join("\n").slice(0,1024)});if(c.length)e.addFields({name:`Comments (${c.length})`,value:c.slice(-3).map(x=>`> **${x.name}:** ${x.txt}`).join("\n").slice(0,1024)});e.setFooter({text:`${b.tag} | ${b.at}`});return e;}
function bugBB(b){const s=b.status,rows=[];const r=new R();if(s==="open")r.addComponents(new B().setCustomId(`cl_${b.id}`).setLabel("Claim").setStyle(S.Primary).setEmoji("🙋"),new B().setCustomId(`rv_${b.id}`).setLabel("Resolve").setStyle(S.Success).setEmoji("✅"),new B().setCustomId(`cx_${b.id}`).setLabel("Close").setStyle(S.Secondary).setEmoji("🔒"),new B().setCustomId(`vu_${b.id}`).setLabel(`${b.votes?.length||0}`).setStyle(S.Secondary).setEmoji("👍"));else if(s==="in-progress")r.addComponents(new B().setCustomId(`rv_${b.id}`).setLabel("Resolve").setStyle(S.Success).setEmoji("✅"),new B().setCustomId(`cx_${b.id}`).setLabel("Close").setStyle(S.Secondary).setEmoji("🔒"),new B().setCustomId(`ua_${b.id}`).setLabel("Unassign").setStyle(S.Secondary).setEmoji("↩️"),new B().setCustomId(`vu_${b.id}`).setLabel(`${b.votes?.length||0}`).setStyle(S.Secondary).setEmoji("👍"));else r.addComponents(new B().setCustomId(`ro_${b.id}`).setLabel("Reopen").setStyle(S.Danger).setEmoji("🔓"),new B().setCustomId(`vu_${b.id}`).setLabel(`${b.votes?.length||0}`).setStyle(S.Secondary).setEmoji("👍"));rows.push(r);rows.push(new R().addComponents(new B().setCustomId(`cm_${b.id}`).setLabel("Comment").setStyle(S.Secondary).setEmoji("💬"),new B().setCustomId(`th_${b.id}`).setLabel("Thread").setStyle(S.Secondary).setEmoji("🧵"),new B().setCustomId(`hi_${b.id}`).setLabel("History").setStyle(S.Secondary).setEmoji("📜")));return rows;}

// LIST / DASH / STATS
function listE(bugs,title){const e=new E().setTitle(title).setColor(0x5865f2).setTimestamp();if(!bugs.length){e.setDescription("No results.");return e;}e.setDescription(bugs.map(b=>`${SEV[b.sev]?.e||""}${ST[b.status]?.e||""} **${b.tag}** ${b.title}${b.toN?" → "+b.toN:""}`).join("\n").slice(0,4000));e.setFooter({text:`${bugs.length} results`});return e;}
function dashE(s,lb){const t=s.total||1,r=(((s.resolved+s.closed)/t)*100).toFixed(1);const bar=(n,em)=>em.repeat(Math.max(0,Math.round((n/t)*20)));return new E().setTitle("📊 Dashboard").setColor(s.critical>0?0xff0000:0x00cc00).setDescription(`**Resolution Rate:** ${r}%\n${bar(s.open,"🟥")+bar(s.prog,"🟧")+bar(s.resolved,"🟩")+bar(s.closed,"⬛")||"░░░░░░░░░░░░░░░░░░░░"}\n\n🟥 ${s.open} | 🟧 ${s.prog} | 🟩 ${s.resolved} | ⬛ ${s.closed}${s.critical>0?`\n\n🚨 **${s.critical} critical!**`:""}`).addFields({name:"Total",value:`${s.total}`,inline:true},{name:"Critical",value:`${s.critical}`,inline:true},{name:"Today",value:`${s.today}`,inline:true}).setTimestamp();}
function statE(s,lb){const e=new E().setTitle("📈 Statistics").setColor(0x5865f2).addFields({name:"Total",value:`${s.total}`,inline:true},{name:"Open",value:`${s.open}`,inline:true},{name:"Progress",value:`${s.prog}`,inline:true},{name:"Resolved",value:`${s.resolved}`,inline:true},{name:"Closed",value:`${s.closed}`,inline:true},{name:"Critical",value:`${s.critical}`,inline:true}).setTimestamp();if(lb?.length)e.addFields({name:"Dev Leaderboard",value:lb.map((d,i)=>`${["🥇","🥈","🥉"][i]||i+1+"."} **${d.name}** ${d.resolved} (${d.spec})`).join("\n")});return e;}
const filtS=()=>new R().addComponents(new SM().setCustomId("filt").setPlaceholder("Filter...").addOptions({label:"All Active",value:"all",emoji:"📋"},{label:"Open",value:"open",emoji:"📂"},{label:"In Progress",value:"in-progress",emoji:"🔧"},{label:"Resolved",value:"resolved",emoji:"✅"},{label:"Critical",value:"s_critical",emoji:"🔴"},{label:"High",value:"s_high",emoji:"🟠"},{label:"Gameplay",value:"c_gameplay",emoji:"🎮"},{label:"Graphics",value:"c_graphics",emoji:"🖼️"},{label:"Network",value:"c_network",emoji:"🌐"},{label:"Performance",value:"c_performance",emoji:"⚡"}));
function annE(title,content,type,by){const t={update:{e:"🔄",c:0x3498db,l:"UPDATE"},patchnote:{e:"📋",c:0x2ecc71,l:"PATCH NOTES"},event:{e:"🎉",c:0xf39c12,l:"EVENT"},important:{e:"🚨",c:0xe74c3c,l:"IMPORTANT"},general:{e:"📢",c:0x5865f2,l:"ANNOUNCEMENT"}};const s=t[type]||t.general;return new E().setColor(s.c).setAuthor({name:`${s.e} ${s.l}`}).setTitle(title).setDescription(content).setFooter({text:`${by} • Studio Bot`}).setTimestamp();}

module.exports={SEV,ST,CT,PL,verifyP,verifyB,bugP,bugBP,adminP,adminBP,tktP,tktBP,tktE,sugP,sugBP,sugC,sugVB,sugAB,betaP,betaBP,betaAP,betaABP,betaC,betaCB,betaSE,rrP,rrB,amP,amB,givE,givB,polE,polB,profE,lbE,bugE,bugBB,listE,dashE,statE,filtS,annE};
