const { EmbedBuilder, ActionRowBuilder, ButtonBuilder, ButtonStyle, StringSelectMenuBuilder } = require("discord.js");
const SEV={critical:{e:"🔴",c:0xff0000,l:"Kritik",bar:"████████"},high:{e:"🟠",c:0xff8c00,l:"Yuksek",bar:"██████░░"},medium:{e:"🟡",c:0xffd700,l:"Orta",bar:"████░░░░"},low:{e:"🟢",c:0x00cc00,l:"Dusuk",bar:"██░░░░░░"}};
const STAT={"open":{e:"📋",l:"Acik",c:0x5865f2},"in-progress":{e:"🔧",l:"Devam",c:0xff8c00},"resolved":{e:"✅",l:"Cozuldu",c:0x00cc00},"closed":{e:"🔒",l:"Kapali",c:0x95a5a6}};
const CAT={gameplay:"🎮 Gameplay",graphics:"🖼️ Grafik",audio:"🔊 Ses",network:"🌐 Network",performance:"⚡ Performans",save:"💾 Kayit",ai:"🤖 AI",other:"📦 Diger"};
const PLAT={pc:"🖥️ PC",playstation:"🎮 PS",xbox:"🎮 Xbox",mobile:"📱 Mobile",all:"🌐 Tumu"};

// ========== VERIFICATION ==========
const verifyPanel=()=>new EmbedBuilder().setColor(0x2ecc71).setAuthor({name:"DOGRULAMA"}).setTitle("━━━━━━━━ Sunucu Girisi ━━━━━━━━").setDescription("```\n   Sunucuya hosgeldin!\n   Kurallari kabul ederek devam et.\n```\n\n**Kurallar:**\n\n> 1. Saygi cercevesinde iletisim kur\n> 2. Spam / flood yapma\n> 3. Reklam / tanitim yasaktir\n> 4. NSFW icerik paylasma\n> 5. Ekip kararlarina uy\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nKurallari okudum ve kabul ediyorum demek icin\nasagidaki butona tikla.").setFooter({text:"Studio Bot v6"}).setTimestamp();
const verifyBtn=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("verify_accept").setLabel("  Kurallari Kabul Ediyorum  ").setStyle(ButtonStyle.Success).setEmoji("✅"));

// ========== BUG PANEL ==========
const bugPanel=()=>new EmbedBuilder().setColor(0x5865f2).setAuthor({name:"BUG TRACKER"}).setTitle("━━━━━━━━ Bug Raporlama ━━━━━━━━").setDescription("```\n    Oyunda hata mi buldun?\n    Raporla, ekip cozum uretiyor!\n```\n\n🔴 `KRITIK ` Oyun cokuyor\n🟠 `YUKSEK ` Buyuk sorun\n🟡 `ORTA   ` Tolere edilir\n🟢 `DUSUK  ` Kozmetik\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n> Her bug raporu **+30 XP** kazandirir!\n> Kritik buglar ekibe otomatik ping atar.").setFooter({text:"Studio Bot v6"}).setTimestamp();
const bugPanelBtns=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("open_report").setLabel("  Bug Raporla  ").setStyle(ButtonStyle.Danger).setEmoji("🐛")),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("my_bugs").setLabel("Raporlarim").setStyle(ButtonStyle.Secondary).setEmoji("📌"),new ButtonBuilder().setCustomId("open_dashboard").setLabel("Dashboard").setStyle(ButtonStyle.Secondary).setEmoji("📊"),new ButtonBuilder().setCustomId("open_leaderboard").setLabel("Liderlik").setStyle(ButtonStyle.Secondary).setEmoji("🏆"))];

// ========== ADMIN PANEL ==========
const adminPanel=(stats,tStats,bStats)=>new EmbedBuilder().setColor(0x2f3136).setAuthor({name:"ADMIN KONTROL MERKEZI"}).setTitle("━━━━━━━━ Yonetim Paneli ━━━━━━━━").setDescription("```\n"+`  📋 Bug Acik    ${String(stats?.open||0).padStart(4)}    🔧 Devam     ${String(stats?.in_progress||0).padStart(4)}\n`+`  ✅ Cozulen     ${String(stats?.resolved||0).padStart(4)}    🔒 Kapali    ${String(stats?.closed||0).padStart(4)}\n`+`  🎫 Ticket Acik ${String(tStats?.open||0).padStart(4)}    🔑 Key Havuz ${String(bStats?.pool||0).padStart(4)}\n`+"```\n"+`🔴 **Kritik:** ${stats?.critical||0} | 📊 **Toplam Bug:** ${stats?.total||0} | 📅 **Bugun:** ${stats?.today||0}`).setTimestamp();
const adminBtns=()=>[
  new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("admin_bugs").setLabel("Buglar").setStyle(ButtonStyle.Primary).setEmoji("📋"),new ButtonBuilder().setCustomId("admin_critical").setLabel("Kritik").setStyle(ButtonStyle.Danger).setEmoji("🚨"),new ButtonBuilder().setCustomId("admin_tickets").setLabel("Ticketlar").setStyle(ButtonStyle.Secondary).setEmoji("🎫"),new ButtonBuilder().setCustomId("admin_refresh").setLabel("Yenile").setStyle(ButtonStyle.Success).setEmoji("🔄")),
  new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("admin_members").setLabel("Uyeler").setStyle(ButtonStyle.Secondary).setEmoji("👥"),new ButtonBuilder().setCustomId("admin_automod").setLabel("AutoMod").setStyle(ButtonStyle.Secondary).setEmoji("🛡️"),new ButtonBuilder().setCustomId("admin_giveaways").setLabel("Cekilisler").setStyle(ButtonStyle.Secondary).setEmoji("🎁"),new ButtonBuilder().setCustomId("admin_stats").setLabel("Istatistik").setStyle(ButtonStyle.Secondary).setEmoji("📈")),
];

// ========== TICKET PANEL ==========
const ticketPanel=(stats)=>new EmbedBuilder().setColor(0xe74c3c).setAuthor({name:"DESTEK MERKEZI"}).setTitle("━━━━━━━━ Destek Ticket ━━━━━━━━").setDescription("```\n   Yardima ihtiyacin mi var?\n   Butona tikla, ozel kanal acilir!\n```\n\n🔧 `Teknik  ` Oyun hatasi/cokme\n👤 `Hesap   ` Giris/ban/hesap\n💰 `Odeme   ` Satin alma/iade\n❓ `Genel   ` Diger konular\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"+`📊 Acik: **${stats?.open||0}** | Kapali: **${stats?.closed||0}**`).setFooter({text:"Destek Sistemi"}).setTimestamp();
const ticketPanelBtns=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("ticket_teknik").setLabel("Teknik").setStyle(ButtonStyle.Danger).setEmoji("🔧"),new ButtonBuilder().setCustomId("ticket_hesap").setLabel("Hesap").setStyle(ButtonStyle.Primary).setEmoji("👤"),new ButtonBuilder().setCustomId("ticket_odeme").setLabel("Odeme").setStyle(ButtonStyle.Success).setEmoji("💰"),new ButtonBuilder().setCustomId("ticket_genel").setLabel("Genel").setStyle(ButtonStyle.Secondary).setEmoji("❓"))];

function ticketEmbed(t) { const cl={teknik:0xe74c3c,hesap:0x3498db,odeme:0x2ecc71,genel:0x95a5a6};const lb={teknik:"🔧 Teknik",hesap:"👤 Hesap",odeme:"💰 Odeme",genel:"❓ Genel"};return new EmbedBuilder().setColor(cl[t.category]||0x5865f2).setAuthor({name:t.tag}).setTitle(lb[t.category]||t.category).setDescription(`>>> ${t.description.slice(0,500)}`).addFields({name:"Olusturan",value:`<@${t.user_id}>`,inline:true},{name:"Durum",value:t.status==="open"?"📋 Acik":"🔒 Kapali",inline:true},{name:"Sahiplenen",value:t.claimed_by?`<@${t.claimed_by}>`:"Henuz yok",inline:true}).setFooter({text:`${t.tag} | ${t.created_at}`}); }

// ========== SUGGESTION PANEL ==========
const suggPanel=()=>new EmbedBuilder().setColor(0xf39c12).setAuthor({name:"ONERI VE GERI BILDIRIM"}).setTitle("━━━━━━━ Oneri / Feedback ━━━━━━━").setDescription("```\n   Oyun hakkinda onerin mi var?\n   Fikrini paylas, topluluk oy versin!\n```\n\n🎮 `Gameplay  ` Mekanikler\n🖼️ `Gorsel     ` Grafik, UI\n🌐 `Topluluk  ` Sunucu, etkinlik\n📦 `Diger     ` Diger\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n> En cok oy alan oneriler ekip tarafindan degerlendirilir!").setFooter({text:"Oneri Sistemi"}).setTimestamp();
const suggPanelBtns=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("sugg_create").setLabel("  Oneri Gonder  ").setStyle(ButtonStyle.Success).setEmoji("💡")),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("sugg_top").setLabel("En Populer").setStyle(ButtonStyle.Secondary).setEmoji("🔥"),new ButtonBuilder().setCustomId("sugg_mine").setLabel("Onerilerim").setStyle(ButtonStyle.Secondary).setEmoji("📌"))];

function suggCard(s) { const st={open:{e:"💡",l:"Acik",c:0xf39c12},approved:{e:"✅",l:"Kabul",c:0x00cc00},rejected:{e:"❌",l:"Red",c:0xff0000},planned:{e:"📋",l:"Planlandi",c:0x3498db},done:{e:"🎉",l:"Yapildi",c:0x9b59b6}}; const t=st[s.status]||st.open; const score=(s.upvotes?.length||0)-(s.downvotes?.length||0); const e=new EmbedBuilder().setColor(t.c).setAuthor({name:`${s.tag} — ${t.e} ${t.l}`}).setTitle(s.title).setDescription(`>>> ${s.description.slice(0,400)}`).addFields({name:"Skor",value:`👍 ${s.upvotes?.length||0}  👎 ${s.downvotes?.length||0}  (net: **${score}**)`,inline:true},{name:"Oneren",value:`<@${s.user_id}>`,inline:true}); if(s.admin_response)e.addFields({name:`${t.e} Ekip (${s.admin_name})`,value:`>>> ${s.admin_response}`}); e.setFooter({text:`${s.tag} | ${s.created_at}`}); return e; }
const suggVoteBtns=(id)=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`svup_${id}`).setLabel("Destekliyorum").setStyle(ButtonStyle.Success).setEmoji("👍"),new ButtonBuilder().setCustomId(`svdn_${id}`).setLabel("Desteklemiyorum").setStyle(ButtonStyle.Secondary).setEmoji("👎"));
const suggAdminBtns=(id)=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`saccept_${id}`).setLabel("Kabul").setStyle(ButtonStyle.Success).setEmoji("✅"),new ButtonBuilder().setCustomId(`splanned_${id}`).setLabel("Plan").setStyle(ButtonStyle.Primary).setEmoji("📋"),new ButtonBuilder().setCustomId(`sreject_${id}`).setLabel("Red").setStyle(ButtonStyle.Danger).setEmoji("❌"),new ButtonBuilder().setCustomId(`sdone_${id}`).setLabel("Yapildi").setStyle(ButtonStyle.Secondary).setEmoji("🎉"));

// ========== BETA PANEL ==========
const betaPanel=(stats)=>new EmbedBuilder().setColor(0x9b59b6).setAuthor({name:"CLOSED BETA"}).setTitle("━━━━━━━ Beta Basvurusu ━━━━━━━").setDescription("```\n   Kapali betaya katilmak ister misin?\n```\n\nBasvur, ekip onaylarsa **beta key** DM ile gelir.\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\n"+`🔑 Havuz: **${stats?.pool||0}** | 📨 Bekleyen: **${stats?.pending||0}**\n✅ Onay: **${stats?.approved||0}** | ❌ Red: **${stats?.rejected||0}**`).setFooter({text:"Beta Program"}).setTimestamp();
const betaPanelBtns=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("beta_apply").setLabel("  Beta Basvur  ").setStyle(ButtonStyle.Success).setEmoji("🔑")),new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("beta_status").setLabel("Durumum").setStyle(ButtonStyle.Secondary).setEmoji("📋"),new ButtonBuilder().setCustomId("beta_stats").setLabel("Istatistik").setStyle(ButtonStyle.Secondary).setEmoji("📊"))];
const betaAdminPanel=(stats)=>new EmbedBuilder().setColor(0xe67e22).setAuthor({name:"BETA KEY YONETIMI"}).setTitle("━━━━━━━ Key Havuzu ━━━━━━━").setDescription("```\n"+`  🔑 Havuz      ${String(stats?.pool||0).padStart(4)}    📦 Dagitilan  ${String(stats?.used||0).padStart(4)}\n`+`  📨 Bekleyen   ${String(stats?.pending||0).padStart(4)}    ✅ Onaylanan  ${String(stats?.approved||0).padStart(4)}\n`+"```").setTimestamp();
const betaAdminBtns=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("beta_addkeys_btn").setLabel("Key Yukle").setStyle(ButtonStyle.Success).setEmoji("🔑"),new ButtonBuilder().setCustomId("beta_pending_btn").setLabel("Bekleyenler").setStyle(ButtonStyle.Primary).setEmoji("📨"),new ButtonBuilder().setCustomId("beta_used_btn").setLabel("Dagitilanlar").setStyle(ButtonStyle.Secondary).setEmoji("📦"),new ButtonBuilder().setCustomId("beta_refresh").setLabel("Yenile").setStyle(ButtonStyle.Secondary).setEmoji("🔄"))];
function betaAppCard(a) { const c={pending:0xf39c12,approved:0x00cc00,rejected:0xff0000};const l={pending:"⏳ Beklemede",approved:"✅ Onaylandi",rejected:"❌ Reddedildi"};const e=new EmbedBuilder().setColor(c[a.status]||0x5865f2).setAuthor({name:`BETA #${a.id}`}).setTitle(l[a.status]||a.status).addFields({name:"Basvuran",value:`<@${a.user_id}>`,inline:true},{name:"Platform",value:a.platform||"?",inline:true},{name:"Tarih",value:a.created_at,inline:true}); if(a.reason)e.setDescription(`>>> ${a.reason.slice(0,500)}`); if(a.reviewed_by)e.addFields({name:"Inceleyen",value:a.reviewed_by,inline:true}); if(a.key_given)e.addFields({name:"Key",value:`\`${a.key_given.slice(0,5)}...\``,inline:true}); e.setFooter({text:`#${a.id}`}); return e; }
const betaAppBtns=(id)=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`betaok_${id}`).setLabel("Onayla").setStyle(ButtonStyle.Success).setEmoji("✅"),new ButtonBuilder().setCustomId(`betano_${id}`).setLabel("Reddet").setStyle(ButtonStyle.Danger).setEmoji("❌"));
const betaStatsEmbed=(s)=>new EmbedBuilder().setTitle("🔑 Beta Istatistik").setColor(0x9b59b6).setDescription("```\n"+`  🔑 Havuz    ${String(s.pool).padStart(4)}    📨 Bekleyen  ${String(s.pending).padStart(4)}\n`+`  ✅ Onay     ${String(s.approved).padStart(4)}    ❌ Red       ${String(s.rejected).padStart(4)}\n`+`  📦 Dagitim  ${String(s.used).padStart(4)}\n`+"```").setTimestamp();

// ========== ROLE PANEL ==========
const rolePanel=()=>new EmbedBuilder().setColor(0x9b59b6).setAuthor({name:"ROL YONETIMI"}).setTitle("━━━━━━━━ Ekip Rolleri ━━━━━━━━").setDescription("👨‍💻 `Developer      ` Yazilimci\n🎨 `3D Artist      ` Modelleme\n🛡️ `Moderator      ` Topluluk\n⭐ `Lead Developer ` Lider\n🧪 `QA Tester      ` Test\n🎵 `Sound Designer ` Ses\n📋 `Game Designer  ` Tasarim\n\n`/role-give @kisi Rol` ile ata\n`/role-remove @kisi Rol` ile al").setTimestamp();

// ========== REACTION ROLE ==========
const reactionRolePanel=()=>new EmbedBuilder().setColor(0x3498db).setAuthor({name:"ROL SEC"}).setTitle("━━━━━━━━ Platform Secimi ━━━━━━━━").setDescription("Hangi platformda oynuyorsun? Tikla ve rolunu al!\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\n\nBirden fazla secebilirsin.").setTimestamp();
const reactionRoleBtns=()=>[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("rrole_PC Player").setLabel("PC").setStyle(ButtonStyle.Secondary).setEmoji("🖥️"),new ButtonBuilder().setCustomId("rrole_PS Player").setLabel("PlayStation").setStyle(ButtonStyle.Secondary).setEmoji("🎮"),new ButtonBuilder().setCustomId("rrole_Xbox Player").setLabel("Xbox").setStyle(ButtonStyle.Secondary).setEmoji("🟢"),new ButtonBuilder().setCustomId("rrole_Mobile Player").setLabel("Mobile").setStyle(ButtonStyle.Secondary).setEmoji("📱"))];

// ========== GIVEAWAY ==========
function giveawayEmbed(g) { const e=new EmbedBuilder().setColor(g.status==="active"?0xf39c12:0x95a5a6).setAuthor({name:"CEKILIS"}).setTitle(`🎁 ${g.prize}`).setDescription(g.status==="active"?`Katilmak icin asagidaki butona tikla!\n\n**Bitis:** <t:${Math.floor(new Date(g.ends_at).getTime()/1000)}:R>\n**Kazanan Sayisi:** ${g.winner_count}\n**Katilimci:** ${g.entries.length}\n\n━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━`:`**Cekilis Sona Erdi!**\n\n**Kazananlar:** ${g.winners_list.map(w=>`<@${w}>`).join(", ")||"Yok"}\n**Katilimci:** ${g.entries.length}`).setFooter({text:`Cekilis #${g.id} | ${g.host}`}).setTimestamp(); return e; }
const giveawayBtn=(id)=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`genter_${id}`).setLabel("Katil").setStyle(ButtonStyle.Success).setEmoji("🎉"));

// ========== POLL ==========
function pollEmbed(p) { const total=p.options.reduce((s,o)=>s+o.votes.length,0)||1; const e=new EmbedBuilder().setColor(p.status==="active"?0x3498db:0x95a5a6).setAuthor({name:p.status==="active"?"ANKET":"ANKET SONA ERDI"}).setTitle(p.question); let desc=p.options.map((o,i)=>{const pct=Math.round(o.votes.length/total*100);const bar="█".repeat(Math.round(pct/5))+"░".repeat(20-Math.round(pct/5));return`**${i+1}.** ${o.text}\n\`${bar}\` ${pct}% (${o.votes.length} oy)`;}).join("\n\n"); if(p.ends_at&&p.status==="active")desc+=`\n\n**Bitis:** <t:${Math.floor(new Date(p.ends_at).getTime()/1000)}:R>`; e.setDescription(desc).setFooter({text:`Anket #${p.id} | ${p.author}`}).setTimestamp(); return e; }
function pollBtns(p) { const rows=[]; for(let i=0;i<p.options.length;i+=4){const row=new ActionRowBuilder();for(let j=i;j<Math.min(i+4,p.options.length);j++){row.addComponents(new ButtonBuilder().setCustomId(`pvote_${p.id}_${j}`).setLabel(`${j+1}. ${p.options[j].text.slice(0,20)}`).setStyle(ButtonStyle.Secondary));}rows.push(row);} return rows; }

// ========== PROFILE CARD ==========
function profileCard(member,rank) {
  const score=(member.invites||0)*50+(member.bugs_reported||0)*30+(member.messages||0);
  const nextLvl=(member.level+1)*100;
  const pct=Math.round((member.xp%100)/100*20);
  const bar="█".repeat(pct)+"░".repeat(20-pct);
  return new EmbedBuilder().setColor(0x5865f2).setAuthor({name:"OYUNCU PROFILI"}).setTitle(member.username||"Bilinmeyen")
    .setDescription(`**Siralama:** #${rank}\n**Skor:** ${score} puan\n\n**Seviye ${member.level}**\n\`${bar}\` ${member.xp} / ${nextLvl} XP`)
    .addFields(
      {name:"📨 Davetler",value:`${member.invites||0}`,inline:true},
      {name:"🐛 Bug Rapor",value:`${member.bugs_reported||0}`,inline:true},
      {name:"💬 Mesajlar",value:`${member.messages||0}`,inline:true},
      {name:"📅 Katilim",value:member.joined_at||"?",inline:true},
    ).setFooter({text:"Skor = Davet×50 + Bug×30 + Mesaj"}).setTimestamp();
}

// ========== LEADERBOARD ==========
function leaderboardEmbed(members) {
  const medals=["🥇","🥈","🥉"];
  const lines=members.slice(0,15).map((m,i)=>{
    const medal=medals[i]||`${i+1}.`;
    return `${medal} **${m.username}** — ${m.score} puan (📨${m.invites||0} 🐛${m.bugs_reported||0} 💬${m.messages||0})`;
  });
  return new EmbedBuilder().setColor(0xf39c12).setAuthor({name:"LIDERLIK TABLOSU"}).setTitle("━━━━━━━━ En Iyi Oyuncular ━━━━━━━━").setDescription(lines.join("\n")||"Henuz veri yok.").setFooter({text:"Skor = Davet×50 + Bug×30 + Mesaj"}).setTimestamp();
}

// ========== AUTOMOD PANEL ==========
function automodPanel(settings) {
  return new EmbedBuilder().setColor(0xe74c3c).setAuthor({name:"OTO-MODERASYON"}).setTitle("━━━━━━━━ AutoMod Ayarlari ━━━━━━━━").setDescription("```\n"+`  Yasakli Kelime    ${String(settings.banned_words?.length||0).padStart(4)} adet\n`+`  Max Caps           %${settings.max_caps_percent||70}\n`+`  Max Mention         ${settings.max_mentions||5}\n`+`  Max Emoji           ${settings.max_emojis||10}\n`+`  Spam Koruma         ${settings.spam_count||5} msg / ${(settings.spam_interval||3000)/1000}sn\n`+"```\n\n**Komutlar:**\n`/automod-word ekle kelime`\n`/automod-word sil kelime`\n`/automod-set ayar deger`").setTimestamp();
}
const automodBtns=()=>new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId("automod_words").setLabel("Yasakli Kelimeler").setStyle(ButtonStyle.Danger).setEmoji("🚫"),new ButtonBuilder().setCustomId("automod_settings").setLabel("Ayarlar").setStyle(ButtonStyle.Secondary).setEmoji("⚙️"));

// ========== BUG CARD ==========
function bugCard(bug,history=[],comments=[]) { const sv=SEV[bug.severity]||SEV.medium,st=STAT[bug.status]||STAT.open; const e=new EmbedBuilder().setColor(sv.c).setAuthor({name:`${bug.tag} — ${st.e} ${st.l}`}).setTitle(bug.title).setDescription(`>>> ${bug.description.slice(0,280)}`); if(bug.steps)e.addFields({name:"Adimlar",value:`\`\`\`\n${bug.steps.slice(0,400)}\n\`\`\``}); e.addFields({name:"Ciddiyet",value:`${sv.e} \`${sv.bar}\``,inline:true},{name:"Platform",value:PLAT[bug.platform]||"?",inline:true},{name:"Kategori",value:CAT[bug.category]||"?",inline:true},{name:"Raporlayan",value:`<@${bug.reported_by}>`,inline:true},{name:"Atanan",value:bug.assigned_to?`<@${bug.assigned_to}>`:"—",inline:true},{name:"Oy",value:`👍 ${bug.upvotes?.length||0}`,inline:true}); if(bug.resolution_note)e.addFields({name:"Cozum",value:`>>> ${bug.resolution_note.slice(0,400)}`}); if(history.length){const t=history.slice(-5).map(h=>`\`${h.at}\` ▸ **${h.action}** (${h.by})`).join("\n");e.addFields({name:"Gecmis",value:t.slice(0,1024)});} if(comments.length){const c=comments.slice(-3).map(c=>`> **${c.author_name}:** ${c.content}`).join("\n");e.addFields({name:`Yorumlar (${comments.length})`,value:c.slice(0,1024)});} e.setFooter({text:`${bug.tag} | ${bug.created_at}`}); return e; }
function bugBtns(bug) { const s=bug.status,rows=[];const r1=new ActionRowBuilder(); if(s==="open")r1.addComponents(new ButtonBuilder().setCustomId(`claim_${bug.id}`).setLabel("Al").setStyle(ButtonStyle.Primary).setEmoji("🙋"),new ButtonBuilder().setCustomId(`resolve_${bug.id}`).setLabel("Coz").setStyle(ButtonStyle.Success).setEmoji("✅"),new ButtonBuilder().setCustomId(`close_${bug.id}`).setLabel("Kapat").setStyle(ButtonStyle.Secondary).setEmoji("🔒"),new ButtonBuilder().setCustomId(`upvote_${bug.id}`).setLabel(`${bug.upvotes?.length||0}`).setStyle(ButtonStyle.Secondary).setEmoji("👍")); else if(s==="in-progress")r1.addComponents(new ButtonBuilder().setCustomId(`resolve_${bug.id}`).setLabel("Coz").setStyle(ButtonStyle.Success).setEmoji("✅"),new ButtonBuilder().setCustomId(`close_${bug.id}`).setLabel("Kapat").setStyle(ButtonStyle.Secondary).setEmoji("🔒"),new ButtonBuilder().setCustomId(`unassign_${bug.id}`).setLabel("Birak").setStyle(ButtonStyle.Secondary).setEmoji("↩️"),new ButtonBuilder().setCustomId(`upvote_${bug.id}`).setLabel(`${bug.upvotes?.length||0}`).setStyle(ButtonStyle.Secondary).setEmoji("👍")); else r1.addComponents(new ButtonBuilder().setCustomId(`reopen_${bug.id}`).setLabel("Yeniden Ac").setStyle(ButtonStyle.Danger).setEmoji("🔓"),new ButtonBuilder().setCustomId(`upvote_${bug.id}`).setLabel(`${bug.upvotes?.length||0}`).setStyle(ButtonStyle.Secondary).setEmoji("👍")); rows.push(r1); rows.push(new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId(`comment_${bug.id}`).setLabel("Yorum").setStyle(ButtonStyle.Secondary).setEmoji("💬"),new ButtonBuilder().setCustomId(`thread_${bug.id}`).setLabel("Tartisma").setStyle(ButtonStyle.Secondary).setEmoji("🧵"),new ButtonBuilder().setCustomId(`history_${bug.id}`).setLabel("Gecmis").setStyle(ButtonStyle.Secondary).setEmoji("📜"))); return rows; }

// ========== MISC ==========
function listEmbed(bugs,title) { const e=new EmbedBuilder().setTitle(title).setColor(0x5865f2).setTimestamp(); if(!bugs.length){e.setDescription("Sonuc yok.");return e;} e.setDescription(bugs.map(b=>`${SEV[b.severity]?.e||""}${STAT[b.status]?.e||""} **${b.tag}** ${b.title}${b.assigned_to_name?" → "+b.assigned_to_name:""}`).join("\n").slice(0,4000)); e.setFooter({text:`${bugs.length} sonuc`}); return e; }
function dashEmbed(stats,lb) { const t=stats.total||1,rate=(((stats.resolved+stats.closed)/t)*100).toFixed(1);const bar=(n,em)=>em.repeat(Math.max(0,Math.round((n/t)*20)));const prog=bar(stats.open,"🟥")+bar(stats.in_progress,"🟧")+bar(stats.resolved,"🟩")+bar(stats.closed,"⬛");return new EmbedBuilder().setTitle("📊 Dashboard").setColor(stats.critical>0?0xff0000:0x00cc00).setDescription(`**Cozum:** ${rate}%\n${prog||"░░░░░░░░░░░░░░░░░░░░"}\n\n🟥 ${stats.open} | 🟧 ${stats.in_progress} | 🟩 ${stats.resolved} | ⬛ ${stats.closed}${stats.critical>0?`\n\n🚨 **${stats.critical} kritik!**`:""}`).addFields({name:"Toplam",value:`${stats.total}`,inline:true},{name:"Kritik",value:`${stats.critical}`,inline:true},{name:"Bugun",value:`${stats.today}`,inline:true}).setTimestamp(); }
function statsEmbed(stats,lb) { const e=new EmbedBuilder().setTitle("📈 Istatistik").setColor(0x5865f2).addFields({name:"Toplam",value:`${stats.total}`,inline:true},{name:"Acik",value:`${stats.open}`,inline:true},{name:"Devam",value:`${stats.in_progress}`,inline:true},{name:"Cozulen",value:`${stats.resolved}`,inline:true},{name:"Kapali",value:`${stats.closed}`,inline:true},{name:"Kritik",value:`${stats.critical}`,inline:true}).setTimestamp(); if(lb?.length)e.addFields({name:"Liderlik",value:lb.map((d,i)=>`${["🥇","🥈","🥉"][i]||i+1+"."} **${d.username}** ${d.bugs_resolved} (${d.specialty})`).join("\n")}); return e; }
const filterSelect=()=>new ActionRowBuilder().addComponents(new StringSelectMenuBuilder().setCustomId("filter_bugs").setPlaceholder("Filtrele...").addOptions({label:"Tum Aktif",value:"all",emoji:"📋"},{label:"Acik",value:"open",emoji:"📂"},{label:"Devam",value:"in-progress",emoji:"🔧"},{label:"Cozulen",value:"resolved",emoji:"✅"},{label:"Kritik",value:"sev_critical",emoji:"🔴"},{label:"Yuksek",value:"sev_high",emoji:"🟠"},{label:"Gameplay",value:"cat_gameplay",emoji:"🎮"},{label:"Grafik",value:"cat_graphics",emoji:"🖼️"},{label:"Network",value:"cat_network",emoji:"🌐"},{label:"Performans",value:"cat_performance",emoji:"⚡"}));

function announceEmbed(title,content,type,author) { const t={update:{e:"🔄",c:0x3498db,l:"GUNCELLEME"},patchnote:{e:"📋",c:0x2ecc71,l:"YAMA NOTLARI"},event:{e:"🎉",c:0xf39c12,l:"ETKINLIK"},important:{e:"🚨",c:0xe74c3c,l:"ONEMLI"},general:{e:"📢",c:0x5865f2,l:"DUYURU"}}; const s=t[type]||t.general; return new EmbedBuilder().setColor(s.c).setAuthor({name:`${s.e} ${s.l}`}).setTitle(title).setDescription(content).setFooter({text:`${author} • Studio Bot`}).setTimestamp(); }

module.exports={SEV,STAT,CAT,PLAT,verifyPanel,verifyBtn,bugPanel,bugPanelBtns,adminPanel,adminBtns,ticketPanel,ticketPanelBtns,ticketEmbed,suggPanel,suggPanelBtns,suggCard,suggVoteBtns,suggAdminBtns,betaPanel,betaPanelBtns,betaAdminPanel,betaAdminBtns,betaAppCard,betaAppBtns,betaStatsEmbed,rolePanel,reactionRolePanel,reactionRoleBtns,giveawayEmbed,giveawayBtn,pollEmbed,pollBtns,profileCard,leaderboardEmbed,automodPanel,automodBtns,bugCard,bugBtns,listEmbed,dashEmbed,statsEmbed,filterSelect,announceEmbed};
